# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LWPx-ParanoidAgent
version:      1.02
version_from: lib/LWPx/ParanoidAgent.pm
installdirs:  site
requires:
    LWP::UserAgent:                0
    Net::DNS:                      0
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
